# -*- coding: utf-8 -*-
"""integer-encoding-simplernn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uY7NEHi59w4FkB8TViwLjUDKxgCA8W5G

## Input Data Preparation
"""

import numpy as np

docs = ['go india',
				'india india',
				'hip hip hurray',
				'jeetega bhai jeetega india jeetega',
				'bharat mata ki jai',
				'kohli kohli',
				'sachin sachin',
				'dhoni dhoni',
				'modi ji ki jai',
				'inquilab zindabad']

!pip install tensorflow

# from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.text import Tokenizer # Import Tokenizer from the new location
tokenizer = Tokenizer(oov_token='<nothing>')

"""Here, the word nothing will be replaced when a new word is inserted by the user inside that given corpus. I did this by creating an object."""

tokenizer.fit_on_texts(docs) # Assign indexes to generate

tokenizer.word_index

tokenizer.word_counts

tokenizer.document_count

sequences = tokenizer.texts_to_sequences(docs)
sequences

"""This will generate sequences. Like the occurences in the sentences. Just because the size of all the sequences in not same, so we have applied padding just to make all the size of the sequneces same.

"""

from keras.utils import pad_sequences

sequences = pad_sequences(sequences,padding='post') # post means adding zeroes after

sequences

"""Now, we can see all the size of sequences is same. Now, the input data is ready."""

from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

"""This imdb dataset is already integer encoded."""

(X_train,y_train),(X_test,y_test) = imdb.load_data()

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

X_train

"""So, number of reviews in training data is 25000."""

X_train[0]

print(len(X_train[2]))
print(len(X_train[1]))

# We can see the length is not same so, we will do the padding I mean the adjusting
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

X_train.shape

"""50 words are there."""

X_train[0]

model = Sequential()

model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

"""Here, I am defining a Sequential model and I am adding a Simple RNN layer which has 32 nodes. I am giving an input shape of 50 timesteps and 1 input features (or 1 word).

## Model Training
"""

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(X_train,
          y_train,
          epochs=10,
          validation_data=(X_test,y_test))

"""As we can see the accuracy is not so good, because we haven't consider all the words. Instead, we have only considered 50 words or may be we need to focus on more epochs like 20 or 30."""

history = model.fit(X_train,
          y_train,
          epochs=10,
          validation_data=(X_test,y_test))

import pandas as pd
df = pd.DataFrame(history.history)

# 3) add an epoch column (1–10)
df.insert(0, "epoch", df.index + 1)

# 4) convert val_accuracy to a percentage, rounded to 2 decimals
df["val_accuracy_pct100"] = (df["val_accuracy"] * 10000).round(2)

df["val_accuracy_str"] = df["val_accuracy"].apply(lambda x: f"{x*100:.2f}")

df.head(10)

